# fly.toml app configuration file generated for grocery-list on 2023-10-19T12:55:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grocery-list"
primary_region = "yul"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
